jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build with flink ${{ matrix.flink-version }}
      run: mvn -B clean verify -pl ${{ matrix.connector }} -am -Dscala-2.12 -Dflink.version=${{
        matrix.flink-version }}
    strategy:
      fail-fast: false
      matrix:
        connector:
        - flink-connector-activemq
        - flink-connector-akka
        - flink-connector-flume
        - flink-connector-influxdb
        - flink-connector-influxdb2
        - flink-connector-kudu
        - flink-connector-netty
        - flink-connector-pinot
        - flink-connector-redis
        - flink-library-siddhi
        flink-version:
        - 1.17.0
        java:
        - '8'
        - '11'
name: Java CI with Maven
on:
  repository_dispatch:
    types: trigger-ga___maven-ci.yml
